### ISSUE TITLE
Support AWS Account ID principal identifier as equivalent to root user IAM ARN

### ISSUE THREAD

**Issue by bflad** [jen20/awspolicyequivalence#3]
Many (most?) AWS services will allow you to submit an IAM policy with the short form principal identifier of just an AWS account ID. Behind the scenes, AWS will convert this identifier to its long form IAM ARN. This seems to confuse quite a few people when they see policies as inequivalent, but look almost identical, at least in Terraform usage.

Example policies that should probably be marked as equivalent:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*",
      "Principal": {
        "AWS": "123456789012"
      }
    }
  ]
}
```

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*",
      "Principal": {
        "AWS": "arn:PARTITION:iam::123456789012:root"
      }
    }
  ]
}
```

**Comment by bflad** [comment]
@jen20 I'd love to fix this up as its a source of confusion -- are you planning on accepting #2? I'd like to avoid rebasing.

**Comment by austinmills** [comment]
Having just been caught by this myself, it would be great to get resolved.

**Comment by jen20** [comment]
@bflad I've just merged #2. Do you have a specific idea on how to fix this?

**Comment by bflad** [comment]
I was thinking for principal string value matching: if it doesn't `==` match then trying to regex match either side to something like `regexp.Compile(fmt.Sprintf("^aws:[^:]+:iam::%s:root$", value))`. If we don't like regex, we can use the AWS SDK `arn` package to try parse for an `arn.ARN` and fetch the `ARN.AccountId` to try matching if its a root IAM principal.

Within `stringPrincipalsEqual` this looks very straightforward, but for `mapPrincipalsEqual` it looks like it would have to be implemented within `awsStringSet.equals()` which is less than ideal. It might be worth splitting this out so we can handle the policies slightly different than everything else. I'll play around in there to see if I can't get it to do what we want easily. Also, very open to ideas. 😄

**Comment by bflad** [comment]
Gave it a shot in #4
